[KIECLOUD-453] - Use unique names for product artifacts
jboss-container-images/rhpam-7-image pull request #438
Opened 2020-11-16 16:38 UTC by spolti

Signed-off-by: spolti <fspolti@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [x] Pull Request title is properly formatted: `[RHPAM-XYZ] Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Attached commits represent units of work and are properly formatted
- [x] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [x] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

2020-11-16 16:41 UTC, msmagnanijr approved these changes

2020-11-17 05:07 UTC, Kaitou786 approved these changes

2020-11-18 09:52 UTC, jakubschwan submitted a review, later dismissed

2020-11-18 20:14 UTC, msmagnanijr submitted a review, later dismissed

2020-11-19 07:58 UTC, jakubschwan requested changes

2020-11-19 07:58 UTC, jakubschwan commented on README.md
> +- name: "rhpam_usiness_central_distribution.zip"
fix typo
```suggestion
- name: "rhpam_business_central_distribution.zip"
```

2020-11-19 10:18 UTC, Kaitou786 approved these changes

2020-11-19 18:17 UTC, spolti commented on README.md
> +- name: "rhpam_usiness_central_distribution.zip"
nice catch :+1:

2020-11-19 19:09 UTC, Kaitou786 approved these changes

2020-11-19 20:23 UTC, msmagnanijr approved these changes

2020-11-20 08:32 UTC, jakubschwan approved these changes

2020-11-20 15:22 UTC, merged